### ISSUE TITLE
web页面

### ISSUE THREAD

**Issue by Rsyncc** [iamazy/elasticsearch-sql#1]
有web页面直接写sql么，请教下大佬，看到支持7.3来看看了

**Comment by iamazy** [comment]
你是要在web页面上执行sql，然后在web页面上返回结果吗？

**Comment by iamazy** [comment]
其实只要下载插件[elasticsearch-sql-plugin](https://github.com/iamazy/elasticsearch-sql/releases),在es中安装之后，在kibana或者postman中使用就行了，不知道你是不是这个意思

**Comment by Rsyncc** [comment]
可以不可以有个web，直接写sql，就能查的




------------------ 原始邮件 ------------------
发件人: "iamazy"<notifications@github.com>; 
发送时间: 2019年8月28日(星期三) 下午3:35
收件人: "iamazy/elasticsearch-sql"<elasticsearch-sql@noreply.github.com>; 
抄送: "清风慕竹"<916431815@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [iamazy/elasticsearch-sql] web页面 (#1)




其实只要下载插件elasticsearch-sql-plugin,在es中安装之后，在kibana或者postman中使用就行了，不知道你是不是这个意思

**Comment by Rsyncc** [comment]
可以有个web地址，直接写sql能查的么

**Comment by iamazy** [comment]
> 
> 
> 可以有个web地址，直接写sql能查的么

你说的不就是kibana吗

**Comment by Rsyncc** [comment]
额，我没看到在哪，我装好了，我的是7.3

**Comment by iamazy** [comment]
> 
> 
> 额，我没看到在哪，我装好了，我的是7.3

[kibana]https://www.elastic.co/cn/downloads/kibana 就是这个

**Comment by Rsyncc** [comment]
我看看，感谢
