### ISSUE TITLE
有java api的案例吗,我将转换后的dsl放入QueryBuilders.wrapperQuery()中会报错

### ISSUE THREAD

**Issue by likeu** [iamazy/elasticsearch-sql#1]
` String sql="select * from novel";`
      `  ElasticSql2DslParser elasticSql2DslParser=new ElasticSql2DslParser();`
   `    ElasticSqlParseResult elasticSqlParseResult = elasticSql2DslParser.parse(sql);`
`        String sqldsl = elasticSqlParseResult.toPrettyDsl(elasticSqlParseResult.toRequest());`
`//        WrapperQueryBuilder wrapperQueryBuilder = QueryBuilders.wrapperQuery("{\"term\": {\"words\":\"2355421\"}}");`
`        WrapperQueryBuilder wrapperQueryBuilder = QueryBuilders.wrapperQuery(sqldsl);`
`       // 设置查询字段`
        `SearchResponse response = elasticsearchTemplate.getClient().prepareSearch()`
          `      .setQuery(wrapperQueryBuilder)`
        `        .setFrom((pageNo-1) * pageSize)`
    `            .setSize(pageNo * pageSize) // 设置一次返回的文档数量，最大值：10000`
    `            .get();`

这是我的测试,不过会报错org.elasticsearch.common.ParsingException: [from] query malformed, no start_object after query name
可以帮忙解决一下吗

**Comment by iamazy** [comment]
没这么用过欸，你要获取querybuilder直接QueryBuilder queryBuilder=elasticSqlParseResult.toRequest().source().query();就行了呀，其实用restClient.search(elasticSqlParseResult.toRequest(),RequestOptions.DEFAULT);就行了

**Comment by iamazy** [comment]
> ` String sql="select * from novel";`
> ` ElasticSql2DslParser elasticSql2DslParser=new ElasticSql2DslParser();`
> ` ElasticSqlParseResult elasticSqlParseResult = elasticSql2DslParser.parse(sql);`
> ` String sqldsl = elasticSqlParseResult.toPrettyDsl(elasticSqlParseResult.toRequest());`
> `// WrapperQueryBuilder wrapperQueryBuilder = QueryBuilders.wrapperQuery("{\"term\": {\"words\":\"2355421\"}}");`
> ` WrapperQueryBuilder wrapperQueryBuilder = QueryBuilders.wrapperQuery(sqldsl);`
> ` // 设置查询字段`
> `SearchResponse response = elasticsearchTemplate.getClient().prepareSearch()`
> ` .setQuery(wrapperQueryBuilder)`
> ` .setFrom((pageNo-1) * pageSize)`
> ` .setSize(pageNo * pageSize) // 设置一次返回的文档数量，最大值：10000`
> ` .get();`
> 
> 这是我的测试,不过会报错org.elasticsearch.common.ParsingException: [from] query malformed, no start_object after query name
> 可以帮忙解决一下吗
没这么用过欸，你要获取querybuilder直接QueryBuilder queryBuilder=elasticSqlParseResult.toRequest().source().query();就行了呀，其实用restClient.search(elasticSqlParseResult.toRequest(),RequestOptions.DEFAULT);就行了

**Comment by iamazy** [comment]
没这么用过欸，你要获取querybuilder直接QueryBuilder queryBuilder=elasticSqlParseResult.toRequest().source().query();就行了呀，其实用restClient.search(elasticSqlParseResult.toRequest(),RequestOptions.DEFAULT);就行了

**Comment by iamazy** [comment]
from size的赋值你直接在sql语句里面用 limit [from],[size]就行了

**Comment by likeu** [comment]
谢谢您，可以用，您可以给我联系方式吗，我可能后面还有问题需要请教您。

**Comment by iamazy** [comment]
QQ: 1448588084
