### ISSUE TITLE
jdbc支持

### ISSUE THREAD

**Issue by techzhou** [iamazy/elasticsearch-sql#10]
请问这个项目目前应该不支持jdbc吧。有什么其他路子可以支持jdbc，用在mybatis上么。

**Comment by iamazy** [comment]
目前不支持jdbc，可以自己实现jdbc接口的

**Comment by techzhou** [comment]
了解:)

**Comment by iamazy** [comment]
你好，现在已经支持JDBC啦 ，见[elasticsearch-sql-jdbc](https://github.com/iamazy/elasticsearch-sql/wiki/Jdbc)
