### ISSUE TITLE
希望补全wiki里面《通用搜索查询》的第四部分

### ISSUE THREAD

**Issue by seniorcandy** [iamazy/elasticsearch-sql#12]
关于fuzzy，prefix，regexp，wildcard这几个查询的例子希望可以补全，
另外
select * from apple where provider like '*苹果*';
这个sql对应的是regexp吧？

**Comment by iamazy** [comment]
是的，主要是之前没考虑好这些模糊搜索用什么样的语法

**Comment by seniorcandy** [comment]
那么不妨支持直接这样
select * from apple where fuzzy(provider, '苹果')

**Comment by iamazy** [comment]
哈哈哈，没看到你回复，我改成了 where provider fuzzy like 'apple' 了

**Comment by seniorcandy** [comment]
多请教一下，请问是否支持not match语法呢？好像没查到呢

**Comment by iamazy** [comment]
> 多请教一下，请问是否支持not match语法呢？好像没查到呢

可以看下[通用搜索查询](https://github.com/iamazy/elasticsearch-sql/wiki/通用搜索查询)，刚加的语法
