### ISSUE TITLE
plugin exception

### ISSUE THREAD

**Issue by GitHub-XiaoChuan** [iamazy/elasticsearch-sql#16]
使用maven install的时候，产生如下错误
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.916 s
[INFO] Finished at: 2020-04-13T16:54:05+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.6:sign (ossrh) on project elasticsearch-sql: Unable to execute gpg command: Error while executing process. Cannot run program "g
pg.exe": CreateProcess error=2, 系统找不到指定的文件。 -> [Help 1]

**Comment by GitHub-XiaoChuan** [comment]
resolved

**Comment by iamazy** [comment]
> resolved

没问题了是吗
