### ISSUE TITLE
请问 README 中的 token relation 和 AST 分别是通过什么工具生成的

### ISSUE THREAD

**Issue by shinux** [iamazy/elasticsearch-sql#28]
token relations 看上去是 echarts 的关系图
AST 好像不是 https://github.com/bkiers/rrd-antlr4  但是也不是 antlr 自带的 gui

**Comment by iamazy** [comment]
> token relations 看上去是 echarts 的关系图
> AST 好像不是 https://github.com/bkiers/rrd-antlr4 但是也不是 antlr 自带的 gui

vscode

**Comment by iamazy** [comment]
feel free to talk in closed issue
