### ISSUE TITLE
有没有文档？

### ISSUE THREAD

**Issue by huangdijia** [iamazy/elasticsearch-sql#3]
都不知道`支持`和`不支持`哪些功能，用es不可能只是简单的`select * from xxx`吧。

**Comment by iamazy** [comment]
好吧，我整理下，test目录下有测试用例你可以看下

**Comment by iamazy** [comment]
支持的功能我下面罗列的呀。。。

**Comment by iamazy** [comment]
简单的写了一下使用的语法[elasticsearch-sql-wiki](https://github.com/iamazy/elasticsearch-sql/wiki)
