### ISSUE TITLE
带hasparent请求报错

### ISSUE THREAD

**Issue by techzhou** [iamazy/elasticsearch-sql#6]
"Caused by: java.lang.ClassNotFoundException: org.elasticsearch.join.query.JoinQueryBuilders",

**Comment by iamazy** [comment]
> "Caused by: java.lang.ClassNotFoundException: org.elasticsearch.join.query.JoinQueryBuilders",

你好，你是什么版本得es

**Comment by techzhou** [comment]
7.3.1

**Comment by iamazy** [comment]
你是不是少引用jar包了

**Comment by iamazy** [comment]
你直接用得我放在readme上得maven仓库得jar吗

**Comment by techzhou** [comment]
plugin install

**Comment by iamazy** [comment]
已更新，[elasticsearch-sql-plugin-v7.3.1.3](https://github.com/iamazy/elasticsearch-sql/releases/download/v7.3.1.3/elasticsearch-sql-plugin-v7.3.1.3.zip),原来得plugin包里少了`org.elasticsearch.plugin:parent-join-client`这个jar包

**Comment by techzhou** [comment]
稳妥
