### ISSUE TITLE
咨询一下，order by desc 中的desc怎么会和desc index冲突

### ISSUE THREAD

**Issue by mahuxiaozi** [iamazy/elasticsearch-sql#7]
order by desc 中的desc怎么会和desc index冲突，能不能优化一下？ desc index能不能限定成describe 规避，这个功能几乎不用的？大量的sql去掉desc 有点麻烦

**Comment by iamazy** [comment]
> order by desc 中的desc怎么会和desc index冲突，能不能优化一下？ desc index能不能限定成describe 规避，这个功能几乎不用的？大量的sql去掉desc 有点麻烦

我之前也考虑过这个问题，可以的，我改下
