### ISSUE TITLE
请教大佬

### ISSUE THREAD

**Issue by lqiiiang911** [iamazy/elasticsearch-sql#8]
请问大佬，sql查询支持布尔值类型查询么，怎么查询呢？

**Comment by iamazy** [comment]
可以的，如果直接等于true或者false不好使，那就将true或者false变成字符串就行了
示例
```sql
select * from student where isExisted=true  这种报错就用下面的
select * from student where isExisted='true'
```

**Comment by lqiiiang911** [comment]
多谢大佬🙏

**Comment by lqiiiang911** [comment]
还有一个问题，原来的字段是long型（比如：880878590978163216），但通过sql查询得到的结果变成这样了（8.808785909781632E17），有什么办法可以解决么？

**Comment by iamazy** [comment]
我怎么没有这个问题，可以截图看一下吗

**Comment by lqiiiang911** [comment]
是我弄错了，现在可以了
