### ISSUE TITLE
请添加Spring项目中引入sql解析和使用RestHighLevelClient请求查询结果的文档

### ISSUE THREAD

**Issue by seniorcandy** [iamazy/elasticsearch-sql#9]
感谢作者的付出，不过相关文档实在太欠缺

**Comment by iamazy** [comment]
你是说和mybatis整合吗？

**Comment by iamazy** [comment]
https://github.com/iamazy/elasticsearch-sql/blob/0c112b0ca32b7ab453b622d9fbc39e2bf2800881/java/src/main/java/io/github/iamazy/elasticsearch/dsl/sql/model/ElasticSqlParseResult.java#L194
