### ISSUE TITLE
JDBC not support 'describe'.

### ISSUE THREAD

**Issue by wellCh4n** [iamazy/elasticsearch-sql#97]
Describe expression could be parsed by ElasticSql2DslParser. But SqlOperation.DESC is assert false in executeQuery.

I implemented an example for this problem.

```
ElasticSqlParseResult parse = PARSER.parse(statement);
org.elasticsearch.action.admin.indices.mapping.get.GetMappingsRequest parseRequest = parse.getMappingsRequest();

// Converting requests, as the old GetMappingsRequest implementation is deprecated in RestHighLevelClient
GetMappingsRequest request = new GetMappingsRequest();
request.indices(parseRequest.indices());

GetMappingsResponse mapping = elasticConnection.getRestClient()
        .indices()
        .getMapping(request, RequestOptions.DEFAULT);
```

But GetMappingsResponse is a complex object, converting to a result set is not so easy because ElasticSearch Mapping is not a two-dimensional table. Such as
```
"name": {
    "type": "text",
    "fields": {
        "keyword": {
            "type": "keyword",
            "ignore_above": 256
        }
    }
}
```
We can convert type information to JSON String, in my opinion. But this does not look very native. Maybe we need to discuss the situation. LFTYR!
In the end, I love this project very much!

**Comment by wellCh4n** [comment]
And... If we use 'assert' to throw exception, we need to add '-ea' to vm options, otherwise the DESC operation will still go to the SELECT logic ~

**Comment by iamazy** [comment]
> Describe expression could be parsed by ElasticSql2DslParser. But SqlOperation.DESC is assert false in executeQuery.
> 
> I implemented an example for this problem.
> 
> ```
> ElasticSqlParseResult parse = PARSER.parse(statement);
> org.elasticsearch.action.admin.indices.mapping.get.GetMappingsRequest parseRequest = parse.getMappingsRequest();
> 
> // Converting requests, as the old GetMappingsRequest implementation is deprecated in RestHighLevelClient
> GetMappingsRequest request = new GetMappingsRequest();
> request.indices(parseRequest.indices());
> 
> GetMappingsResponse mapping = elasticConnection.getRestClient()
>         .indices()
>         .getMapping(request, RequestOptions.DEFAULT);
> ```
> 
> But GetMappingsResponse is a complex object, converting to a result set is not so easy because ElasticSearch Mapping is not a two-dimensional table. Such as
> 
> ```
> "name": {
>     "type": "text",
>     "fields": {
>         "keyword": {
>             "type": "keyword",
>             "ignore_above": 256
>         }
>     }
> }
> ```
> 
> We can convert type information to JSON String, in my opinion. But this does not look very native. Maybe we need to discuss the situation. LFTYR! In the end, I love this project very much!

@wellCh4n , Thanks! What about flatten JSON into a two-dimensional table, e.g.

from

```json
"name": {
    "type": "text",
    "fields": {
        "keyword": {
            "type": "keyword",
            "ignore_above": 256
        }
    }
}
```
to
```json
{
   "name.type": "text",
   "name.fields.keyword.type": "keyword",
   "name.fields.keyword.ignore_above": 256
}
```

**Comment by wellCh4n** [comment]
> > Describe expression could be parsed by ElasticSql2DslParser. But SqlOperation.DESC is assert false in executeQuery.
> > I implemented an example for this problem.
> > ```
> > ElasticSqlParseResult parse = PARSER.parse(statement);
> > org.elasticsearch.action.admin.indices.mapping.get.GetMappingsRequest parseRequest = parse.getMappingsRequest();
> > 
> > // Converting requests, as the old GetMappingsRequest implementation is deprecated in RestHighLevelClient
> > GetMappingsRequest request = new GetMappingsRequest();
> > request.indices(parseRequest.indices());
> > 
> > GetMappingsResponse mapping = elasticConnection.getRestClient()
> >         .indices()
> >         .getMapping(request, RequestOptions.DEFAULT);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But GetMappingsResponse is a complex object, converting to a result set is not so easy because ElasticSearch Mapping is not a two-dimensional table. Such as
> > ```
> > "name": {
> >     "type": "text",
> >     "fields": {
> >         "keyword": {
> >             "type": "keyword",
> >             "ignore_above": 256
> >         }
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > We can convert type information to JSON String, in my opinion. But this does not look very native. Maybe we need to discuss the situation. LFTYR! In the end, I love this project very much!
> 
> @wellCh4n , Thanks! What about flatten JSON into a two-dimensional table, e.g.
> 
> from
> 
> ```json
> "name": {
>     "type": "text",
>     "fields": {
>         "keyword": {
>             "type": "keyword",
>             "ignore_above": 256
>         }
>     }
> }
> ```
> 
> to
> 
> ```json
> {
>    "name.type": "text",
>    "name.fields.keyword.type": "keyword",
>    "name.fields.keyword.ignore_above": 256
> }
> ```

@iamazy Thanks for your reply.
Flatten is a good idea! But the number of columns in the ResultSet becomes **uncertain**.
For MySQL, the result set described is a two-dimensional table with a determined number of rows.
<img width="530" alt="image" src="https://user-images.githubusercontent.com/13273026/197135527-cb3db184-2902-446a-8c24-7891a7c5f68c.png">
If we flatten the result, the result will be
<img width="581" alt="image" src="https://user-images.githubusercontent.com/13273026/197136445-2cee46e1-5448-4b76-8f5c-cabd7d4b87ae.png">

I tried ClickHouse and the results are not the same as MySQL.
![image](https://user-images.githubusercontent.com/13273026/197136902-e93067a0-f4e2-4722-bfc9-14d3a71f18db.png)

I understand that different database types, people are able to accept desc's return differently. So I tend to convert the other fields to JSON String. In my opinion, this is the most intuitive. e.g.
<img width="535" alt="image" src="https://user-images.githubusercontent.com/13273026/197139416-20184457-894e-4104-98f5-93c1814cfff2.png">

**Looking forward to your suggestions!** 😆

**Comment by wellCh4n** [comment]
But ElasticSearch is a document(JSON)-based database. Is there no need to think about other databases, the original mapping as a return is ok.

**Comment by iamazy** [comment]
> I understand that different database types, people are able to accept desc's return differently. So I tend to convert the other fields to JSON String. In my opinion, this is the most intuitive. e.g.
> <img width="535" alt="image" src="https://user-images.githubusercontent.com/13273026/197139416-20184457-894e-4104-98f5-93c1814cfff2.png">

I think this way is a better choice, do you willing to submit a pr?

**Comment by wellCh4n** [comment]
> > I understand that different database types, people are able to accept desc's return differently. So I tend to convert the other fields to JSON String. In my opinion, this is the most intuitive. e.g.
> > <img alt="image" width="535" src="https://user-images.githubusercontent.com/13273026/197139416-20184457-894e-4104-98f5-93c1814cfff2.png">
> 
> I think this way is a better choice, do you willing to submit a pr?

That's great!
I will commit a PR this weekend~ And, how about changing 'info' to 'extra' in reference to MySQL?

**Comment by iamazy** [comment]
> > > I understand that different database types, people are able to accept desc's return differently. So I tend to convert the other fields to JSON String. In my opinion, this is the most intuitive. e.g.
> > > <img alt="image" width="535" src="https://user-images.githubusercontent.com/13273026/197139416-20184457-894e-4104-98f5-93c1814cfff2.png">
> > 
> > 
> > I think this way is a better choice, do you willing to submit a pr?
> 
> That's great! I will commit a PR this weekend~ And, how about changing 'info' to 'extra' in reference to MySQL?

That's OK
